### ISSUE TITLE
installing block from system designer fails

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/nio_command#16]
An error message is displayed, and terminal logs the following, when installing this block. It looks like the requirements for the oauth submodule are not being installed.
```
[2018-07-17T22:30:59.669339Z] NIO [ERROR] [main.WebHandler] Exception
Traceback (most recent call last):
  File "/home/pi/nio/env/lib/python3.5/site-packages/niocore/modules/web/cherrypy/handler.py", line 84, in _do_cal$
    handler_callback(request, response, *args, **kwargs)
  File "/home/pi/nio/env/lib/python3.5/site-packages/niocore/components/project_manager/handler.py", line 125, in $
    url, tag, path_to_block, branch
  File "/home/pi/nio/env/lib/python3.5/site-packages/niocore/components/project_manager/manager.py", line 398, in $
    raise RuntimeError(errors)
RuntimeError: {'blocks.nio_command.oauth2_mixin.oauth2_service': "No module named 'oauth2client'", 'blocks.nio_com$
```

**Comment by ssclay** [comment]
Are you using a systemd service and virtual environment on a raspberry pi?

**Comment by shadetree01010100** [comment]
Great insight @ssclay , it turns out that this is an issue with my virtual environment.
